---
#  install.yml file for redis
- name: install dependencies
  apt: pkg={{ item }} 
    update_cache=yes 
    cache_valid_time=86400 
    state=present
  with_items:
    - gcc
    - make
    - libc6-dev
  when: ansible_os_family == "Debian"

- name: enable memory overcommit
  sysctl: name=vm.overcommit_memory 
    value=1
    state=present
    reload=yes 
    ignoreerrors=yes

- name: download redis
  get_url: 
    url=http://download.redis.io/releases/redis-{{ redis_version }}.tar.gz
    dest=/usr/local/src/redis-{{ redis_version }}.tar.gz

- name: extract redis
  shell: tar xf /usr/local/src/redis-{{ redis_version }}.tar.gz -C /usr/local/src
    creates=/usr/local/src/redis-{{ redis_version }}

- name: compile
  command: make -j5
    chdir=/usr/local/src/redis-{{ redis_version }}
    creates=/usr/local/src/redis-{{ redis_version }}/src/redis-server

- name: create redis directory
  file: path={{ redis_install_dir }} state=directory

- name: create /etc/redis
  file: path=/etc/redis state=directory

- name: add redis user
  user:
    name={{ redis_user }}
    comment="Redis owner"
    home={{ redis_install_dir }}
    shell=/bin/false
    system=yes

- name: create /var/run/redis
  file: path=/var/run/redis state=directory
        owner={{ redis_user }}

- name: install
  command: make PREFIX={{ redis_install_dir }} install
           chdir=/usr/local/src/redis-{{ redis_version }}
           creates={{ redis_install_dir }}/bin/redis-server
